# prompts/v6_3.py
from .utils import truncate_to_n_tokens

def build_baseline_prompt_v6_3(instruction: str) -> str:
    """
    Uppercase variant of v6 baseline (con nota 'no errors' / clean code).
    """
    return f"""# PYTHON LIBRARY-BASED CODE GENERATION TASK

YOUR OBJECTIVE IS TO GENERATE A **COMPLETE, SINGLE PYTHON 3 FILE** THAT DIRECTLY
SOLVES THE TASK DESCRIBED BELOW. THIS TASK REQUIRES SIGNIFICANT UTILIZATION OF A SPECIFIC
PYTHON LIBRARY, WHICH SHOULD BE INFERRED FROM THE TASK DESCRIPTION.

---

## TASK DESCRIPTION

{instruction.strip()}

---

## IMPLEMENTATION REQUIREMENTS & OUTPUT FORMAT

**CODE REQUIREMENTS:**
- THE OUTPUT MUST BE A SINGLE, RUNNABLE PYTHON 3 SCRIPT OR A SELF-CONTAINED MODULE.
- HEAVILY UTILIZE THE TARGET PYTHON LIBRARY'S APIS. YOUR SOLUTION SHOULD DEMONSTRATE
  EFFECTIVE USE OF THE LIBRARY.
- PRODUCE CLEAN, PRODUCTION-QUALITY PYTHON 3 CODE.
- INCLUDE TYPE HINTS FOR ALL FUNCTION SIGNATURES AND IMPORTANT VARIABLES.
- WRITE A CLEAR DOCSTRING FOR ANY PRIMARY FUNCTIONS OR CLASSES YOU DEFINE.
- ADHERE TO PEP 8 STYLE GUIDELINES.
- IF THE TASK INVOLVES CREATING A REUSABLE FUNCTION OR CLASS, DEMONSTRATE ITS
  USAGE WITHIN THE SCRIPT OR PROVIDE A SIMPLE UNIT TEST.
- ENSURE ALL NECESSARY IMPORTS FROM THE TARGET LIBRARY (AND STANDARD PYTHON LIBRARIES)
  ARE INCLUDED AT THE BEGINNING OF THE FILE.
- THE SCRIPT MUST NOT GIVE RRORS AND BE A HIGH-QUALITY CLEAN CODE

**OUTPUT:**
- PROVIDE **ONLY** THE PYTHON CODE FOR THE SINGLE FILE.
- DO NOT INCLUDE ANY SURROUNDING TEXT, EXPLANATIONS, OR MARKDOWN FORMATTING
  (PYTHON COMMENTS AND DOCSTRINGS ARE ENCOURAGED WITHIN THE CODE).
- START YOUR CODE IMMEDIATELY FOLLOWING THE ```PYTHON MARKER.

```PYTHON
"""

def build_rag_prompt_v6_3(instruction: str, retrieved: str) -> str:
    """
    Uppercase variant of v6 RAG (con nota 'no errors' / clean code).
    """
    retrieved_snippet = truncate_to_n_tokens(retrieved, 1800)
    return f"""# PYTHON LIBRARY-BASED CODE GENERATION TASK (WITH CONTEXT)

YOU ARE AN EXPERT PYTHON ENGINEER. YOUR OBJECTIVE IS TO GENERATE A **COMPLETE,
SINGLE PYTHON 3 FILE** THAT DIRECTLY SOLVES THE 'TASK DESCRIPTION' BELOW.
THIS TASK REQUIRES SIGNIFICANT UTILIZATION OF A SPECIFIC PYTHON LIBRARY.
YOU ARE PROVIDED WITH 'RETRIEVED CODE EXAMPLES' FROM THIS LIBRARY TO GUIDE YOUR IMPLEMENTATION. THE SCRIPT MUST NOT GIVE RRORS AND BE A HIGH-QUALITY CLEAN CODE

---

## RETRIEVED CODE EXAMPLES (CONTEXTUAL GUIDANCE)

```PYTHON
{retrieved_snippet.strip()}
"""
